---
title: "Simulation"
author: "Sarahy Martinez"
date: "2024-10-31"
output: github_document
---


```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%:"
  
)


theme_set(theme_minimal()+ theme(legend.position = "bottom"))


options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
```


## Lets simulate something 

I have a function

```{r}

sim_mean_sd= function(sample_size, mu =3 , sigma = 4 ) {
  
  
  sim_data=
    
  tibble(
    
    x= rnorm(n= sample_size, mean = mu, sd=sigma)  # creating a tibble (table of values), with diff mean and SD
  )

  
sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

}


```



I can simulate by running this line

```{r}

sim_mean_sd(30)  # we can rerun but suppose we do this over and over what do the distributions of means look like? 
```


## Lets simulate alot... 
How can we actually formally do this in a way where we dont have to run the same line of code over and over again 

Lets start with a for loop.  

We need the output and the for loop itself 


```{r}

output = vector("list", length = 100)

for (i in 1:100){     #if this is all we do will run over and over, so need output when you run and say i=3, 4, 5 etc 
  
  output[[i]]= sim_mean_sd(sample_size = 30)    # if we just run the output will return all 100 mean and sd
  
  
}




# take the list and bind rows will be more managable and creates a tibble 


bind_rows(output)
# this is 100 times I've gone into the universe and got the mean and sd, this is what happened the first time, second, etc. 
```




















